### ISSUE TITLE
Saving to tape file

### ISSUE THREAD

**Issue by turbocat2001** [begoon/rk86-js#2]
Hello, can you save the program to a file? I just wrote a program and there is no way to save it! Neither binary nor text!

**Comment by begoon** [comment]
If you write programming in Assembler tab, you can copy-paste from there.

If you write directly in machine code in the Monitor, you can open Console and use 'z' to disassemble your code, and then copy and paste.

There is no way at the moment to download RK memory just as a binary.

**Comment by begoon** [comment]
Actually, I am going to add a feature to download the emulator memory, fully or partially, as a binary. Should are done in a day or two.

**Comment by begoon** [comment]
@turbocat2001 I have just pushed a new version 1.52 with `Save memory` button and `dd` command in the console.

`Save memory` button downloads RK memory, all 64KB, as binary.

`dd` command allows to download a chunk of memory with given start address and length.

For example: 

`] dd 0, 0x100` downloads the first 256 bytes of memory.

`] dd 0xf800, 0x800` downloads the last 2k of memory containing Monitor.
